twa.df<-mtcars; str(twa.df)
library(dplyr)
twa.df <- twa.df%>%select(mpg,am,cyl); str(twa.df)
twa.df$am <- factor(twa.df$am)
twa.df$cyl <- factor(twa.df$cyl)
str(twa.df)
library(psych) 
describeBy(twa.df$mpg, twa.df$am:twa.df$cyl, mat=T)
plot(mpg ~ am + cyl, data=twa.df) 
boxplot(mpg ~ am*cyl, data=twa.df)
